import { NextResponse } from "next/server";
import { type CvLead } from "../../../../lib/cv-access";
import { appendCvLeadEvent, isGoogleSheetsConfigured } from "../../../../lib/google-sheets";

export const runtime = "nodejs";

function unauthorized(status = 404) {
  return NextResponse.json({ ok: false, error: "Not found." }, { status });
}

function isAuthorized(request: Request) {
  const configuredToken = process.env.CV_ADMIN_TOKEN;

  if (!configuredToken) {
    return false;
  }

  const header = request.headers.get("authorization") || "";
  const token = header.startsWith("Bearer ") ? header.slice(7).trim() : "";

  return token === configuredToken;
}

function buildSmokeTestLead(): CvLead {
  const now = new Date().toISOString();

  return {
    fullName: "CV Access Smoke Test",
    professionalEmail: "smoke-test@example.com",
    whatsapp: "+55 00 00000-0000",
    company: "Ricardo Zulkiewicz",
    role: "Production diagnostics",
    linkedin: "",
    cvVersion: "pt-br-commercial",
    reason: "Google Sheets persistence smoke test generated from protected diagnostics endpoint.",
    message: "This row can be deleted after production validation.",
    consent: true,
    requestedAt: now,
  };
}

export async function POST(request: Request) {
  if (!isAuthorized(request)) {
    return unauthorized(process.env.CV_ADMIN_TOKEN ? 401 : 404);
  }

  if (!isGoogleSheetsConfigured()) {
    return NextResponse.json(
      {
        ok: false,
        status: "google_sheets_not_configured",
        message:
          "Google Sheets persistence is not configured. Set GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL, GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY and CV_LEADS_SPREADSHEET_ID.",
      },
      { status: 424 }
    );
  }

  const result = await appendCvLeadEvent({
    status: "request_submitted",
    lead: buildSmokeTestLead(),
    request,
    notes: "Smoke test row generated by /api/cv/diagnostics/google-sheets-test.",
  });

  return NextResponse.json({
    ok: result.appended,
    status: result.appended ? "google_sheets_append_ok" : "google_sheets_append_failed",
    result,
  }, { status: result.appended ? 200 : 500 });
}

export async function GET(request: Request) {
  return POST(request);
}
